### ISSUE TITLE
New version of PatchPerl

### ISSUE THREAD

**Issue by pukku** [gugod/patchperl-packing#9]
Hi! PatchPerl is now at 1.48, while you're still delivering 1.38, which means that PerlBrew won't install 5.24 on Mac OS X Sierra...

**Comment by gugod** [comment]
Thanks for the report. This repo is supposed to be updated by a cronjob, which was broken with my system upgrade (*doh*). But it's now fixed, and should be updated shortly after a new patchperl release.
